<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net8.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AcNativeLibraryResolver\AcNativeLibraryResolver.csproj" />
	</ItemGroup>

	<!-- Uncomment to have AutoCAD process killed when you build the project
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="taskkill /F /IM acad.exe &gt;nul 2&gt;&amp;1 || exit 0" />
	</Target>
	-->

</Project>
